name: Setup Preview Environment For Dashboard

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-preview:
    environment:
      name: preview
      url: https://pr-${{ github.event.number }}.coffeewithegg.com
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
    env:
      AWS_REGION: ap-southeast-2
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build app and dependencies
        run: pnpm build:ci

      - name: Prepare preview prefix
        run: echo "SST_STAGE=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Deploy Preview
        run: |
          cd apps/dashboard
          pnpm turbo deploy
        env:
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
          SST_PRINT_LOGS: true
